site_name: p5.js workshop

theme:
    name: material
    language: ja
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - content.code.copy
        - navigation.footer

nav:
    - はじめに: index.md
    - intro: intro.md
    - Level 0: level_0.md
    - Level 1: level_1.md
    - Level 2: level_2.md
    - Level 3: level_3.md

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences